{% set name = "spiceql" %}
{% set version = "dev" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: .
    path: ../
    # url: https://code.usgs.gov/astrogeology/spiceql/-/archive/{{ version }}/spiceql-{{ version }}.tar.gz
    # sha256: df51ef41839b8d4e09153922ddf272c2da862fc0f126b35d978d8ff81ce8044e
  # submodules
  - folder: submodules/gularkfilesystem
    url: https://github.com/gulrak/filesystem/archive/fcea331ebb8273581cef3e91a131e3d7877f7dfd.zip
    sha256: c2775dccc5d8f6d8654bd4b1ef2302b26b8cb75f140640dc2328a58d643f3818
  - folder: submodules/googletest
    url: https://github.com/google/googletest/archive/e47544ad31cb3ceecd04cc13e8fe556f8df9fe0b.zip
    sha256: d87a66523023173ea842e5ec6eb969a54d20be2b56cd939dd6d808fda57626fa
  - folder: submodules/json
    url: https://github.com/nlohmann/json/archive/fac07e22c5d7dd0423ccf31c02db5603d27e6556.zip
    sha256: 191543fd27175d57bd6d2f56cb4f63e424cb56379acb6f367bad3ce34a2bb9c3
  - folder: submodules/hippomocks
    url: https://github.com/dascandy/hippomocks/archive/10960d027b398444ec3ec6ce2487de3db0283ff8.zip
    sha256: a4efc07eacdc35107039bd3b7b491b9fc5f95d4dabb37de83a2b0642c7231fe8
  - folder: submodules/BTree
    url: https://github.com/frozenca/BTree/archive/ff6881996ff3c46ded564f92bc589fcbd218df00.zip
    sha256: 1ca35dc6898f36711219d92c9d0763ff187af9b9d1ae9385377322b45dfb3f4e

build:
  number: 0
  skip: true  # [win]

requirements:
requirements:
  build:
    - {{ compiler('cxx') }} =18 # [osx]
    - {{ compiler('cxx') }} # [linux]
    - make
    - swig
    - cmake-no-system >=3.14

  host:
    - setuptools
    - cpp-filesystem
    - pip
    - cereal
    - highfive
    - cspice
    - hdf5
    - fmt >9,<10
    - spdlog =1.12
    - openssl
    - python
    - libcurl

  run:
    - python
    - cspice
    - hdf5
    - libcurl


test:
  imports:
    - pyspiceql
  commands:
    - test -e $PREFIX/lib/libSpiceQL${SHLIB_EXT}  # [unix]
    - test -e $PREFIX/include/SpiceQL/config.h  # [unix]
    - if not exist %LIBRARY_BIN%\SpiceQL.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\SpiceQL.lib exit 1  # [win]

about:
  home: https://code.usgs.gov/astrogeology/spiceql
  summary: "This Library provides a C++ interface querying, reading and writing Naif SPICE kernels."
  license: CC0-1.0
  license: LICENSE.txt
  doc_url: https://sugar-spice.readthedocs.io/en/latest/#docs
  dev_url: https://code.usgs.gov/astrogeology/spiceql

extra:
  recipe-maintainers:
    - Kelvinrr
    - chkim-usgs
