site_name: "SpiceQL Manual"

theme:
  name: material
  palette:
    scheme: slate
  # favicon: assets/favicon.ico
  site_name_style: bold
  title_style: light 
  icon:
    annotation: material/chevron-right-circle
  font:
    text: Inter
    code: Roboto Mono

  highlightjs: true
  components:
    site_name: true
    title: false
    menu: false
    preview: true
    footer: false

  features:
      - navigation.tabs
      - navigation.path
      - navigation.indexes
      - search.suggest
      - search.suggest
      - content.tabs.link

extra_css: 
  - assets/extra.css

nav:
  - index.md
  - "[ C++ API ]":
      - 'Namespaces':
          - 'Namespace List': 'SpiceQLCPPAPI/namespaces.md'
          - 'Functions': 'SpiceQLCPPAPI/namespace_member_functions.md'
  - "[ RESTful API ]": 
      - 'OpenAPI Docs': 'RestAPI.md' 
  - "[ USGS Astrogeology Docs ]" : https://astrogeology.usgs.gov/docs/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences 
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  - swagger-ui-tag
  - mkdoxy:
      projects:
        SpiceQLCPPAPI: 
          src-dirs: SpiceQL/include/
          FILE_PATTERNS: 'api.h inventory.h'  
          full-doc: True # if you want to generate full documentation
          doxy-cfg: # standard doxygen configuration (key: value)
            RECURSIVE: false # recursive search in source directories
